export const resume = {
  personalInformation: {
    location: "Louisville, KY",
    phone: "346-219-1755",
    email: "haquoctong59@gmail.com",
    github: "github.com/KevinHa59",
    linkedin: "linkedin.com/in/tong-ha",
    website: "tongha.dev",
  },
  introduction:
    "I'm a seasoned Software Developer with 2.5 years of industry experience, specializing in frontend and backend development. <br/><br/>My expertise lies in crafting robust web applications using technologies like ReactJS, NextJS, Node.js, and Spring Boot. Throughout my career, I've played key roles in delivering high-impact projects, from collaborating with teams on school management systems to independently visualizing complex data structures.<br/><br/>With a passion for innovation and a track record of success, I'm committed to delivering exceptional results in every project I undertake. Let's connect and discuss how I can bring value to your team.",
  summary:
    "My name is Tong Ha, a graduate student with Bachelor of Computer Science degree with a passion in Software Development. Strong knowledge in ReactJS, Redux, OOP, Hibernate, Spring Boot, Relational Database. Experienced team leader skilled in Java and MySQL.",
  skills: {
    frontend: [
      "React JS",
      "Next JS",
      "JavaScript",
      "Redux",
      "Axios",
      "Bootstrap",
      "Material UI",
    ],
    backend: ["Nodejs", "Azure Function", "Java", "Spring Boot"],
    webservice: ["REST", "REST API"],
    database: ["MySQL", "SQL Server", "MongoDB"],
    sdlc: ["Agile"],
    versionControl: ["Git"],
    ide: [
      "IntelliJ IDEA",
      "Visual Studio Code",
      "Microsoft SQL Server",
      "MySQL Workbench",
    ],
    os: ["Windows"],
    language: [
      "Vietnamese (Native Speaker)",
      "English (Speaking, Reading, Writing, Listening)",
    ],
  },
  education: [
    {
      institution: "University of Houston-Downtown",
      location: "Houston, TX",
      degree: "Bachelor of Computer Science",
      dates: "January 2020 - December 2021",
      gpa: "3.94",
      honors: ["Dean's List, 3 semesters"],
      relevantCoursework: [
        "Software Engineering",
        "Database Systems",
        "Digital Logic",
        "Object-Oriented Programming",
        "Intro to Theory of Computation",
        "Web Programming",
        "Programming Language Concepts",
        "Operating Systems",
        "Data and Information Structures",
        "IoT",
        "Natural Language Processing",
      ],
    },
    {
      institution: "Houston Community College",
      location: "Houston, TX",
      degree: "Computer Science, Information Technology",
      dates: "",
      gpa: "3.24",
      honors: ["Dean's List, 3 semesters", "Honor's List, 3 semesters"],
      relevantCoursework: [
        "Computer Application I",
        "Programming Fundamental I, II, and III",
        "Computer Organization",
      ],
    },
  ],
  projects: [
    {
      dates: "January 2020 - May 2020",
      title: "School Management Project",
      institution: "University of Houston-Downtown",
      location: "Houston, TX",
      role: "Team Leader",
      description:
        "Collaborated with a group of 5 to the design and stimulate application's UI, functions, database, and report for a desktop application delivering University services where professors and students manage their courses.",
      technologiesUsed: [
        "Java",
        "Spring Boot",
        "React JS",
        "HTML5",
        "CSS3",
        "JavaScript",
        "Redux",
        "MySQL",
        "GIT",
      ],
    },
    {
      dates: "August 2020 - December 2020",
      title: "Binary Search Tree Visualization Project",
      institution: "University of Houston-Downtown",
      location: "Houston, TX",
      role: "Independent",
      description:
        "Design a desktop app visualizing how a binary search tree work with several functions such as Add Node, Search Node, Remove Node, Find Lowest Common Ancestor.",
      technologiesUsed: ["Java", "JavaFX", "CSS"],
    },
  ],
  experience: [
    {
      dates: "June 2022 - Current",
      company: "Phase Ortho",
      location: "Kentucky, United States",
      position: "Software Developer",
      responsibilities: [
        "Team up with other developers to analysis the existed local production application and planning to move that application to Cloud.",
        "Develop Production Web App on Cloud with React JS, JavaScript, HTML, CSS, Python, SQL Database Azure Function, Azure Database, Azure Static Web App.",
        "Improve the performance of Cloud Application using Next JS.",
        "Expand the speed of development by using third library of style Material Ul.",
        "Share and review code using GIT. Also, setup CI/CD the deployment of Web App to Azure Static Web App through GIT.",
        "Create Azure functions using Python to communicate with SQL Database on Azure Database.",
      ],
      technologiesUsed: [
        "React JS",
        "HTML",
        "CSS",
        "JavaScript",
        "Python",
        "GIT",
        "Azure",
        "SQL Database",
      ],
    },
    {
      dates: "January 2017 - December 2017",
      company: "DICENTRAL LTD",
      location: "Vietnam",
      position: "Frontend Intern",
      responsibilities: [
        "Business process analysis and problem solving of data quality and maintenance issues, including system development and user-interface.",
        "Develop UIs with HTML, CSS, Javascript.",
        "Extensively involved in coding with ReactJS to add functionalities and effects to UI.",
      ],
      technologiesUsed: ["React JS", "HTML", "CSS", "Javascript", "GIT"],
    },
  ],
};

console.log(resume);
